"""update date field

Revision ID: 6ce89d340dc1
Revises: f56383289cef
Create Date: 2022-09-29 22:22:48.985995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce89d340dc1'
down_revision = 'f56383289cef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('date', sa.Date(), nullable=False))
    op.drop_column('todos', 'due_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('todos', 'date')
    # ### end Alembic commands ###
